#!/bin/bash

pip3 install --upgrade pip
pip3 install -r requirements.txt

# Move NetScan to ~/bin and make it executable
cp SoftwareBuster /usr/local/bin/
chmod +x /usr/local/bin/SoftwareBuster

echo "Software Buster has been moved to /usr/local/bin/"
echo "To run the script please use: python3 SoftwareBuster file.txt"
